apiVersion: v1
kind: Pod
metadata:
  name: happypanda
  namespace: dev-service1
  labels: 
    app: redis
    segment: backend
    company: mycompany    
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - name: redisport
      containerPort: 6379
      protocol: TCP
  nodeSelector:
    hostname: node01