apiVersion: v1
kind: Pod
metadata:
  name: happyelephant
  namespace: dev-service2
  labels:
    app: redis
    segment: frontend
    company: mycompany
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - name: redisport
      containerPort: 6379
      protocol: TCP