apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: contino
  labels:
    app: nginx
    segment: frontend
    company: contino
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - name: web
        containerPort: 80
        protocol: TCP